-- MySQL Script generated by MySQL Workbench
-- Thu Aug 12 11:42:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoJava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoJava` DEFAULT CHARACTER SET utf8 ;
USE `projetoJava` ;

-- -----------------------------------------------------
-- Table `projetoJava`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `icone` VARCHAR(45) NULL,
  `exibir` INT NOT NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_Perfil1_idx` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `projetoJava`.`Perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`menu_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`menu_perfil` (
  `idMenu` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idMenu`, `idPerfil`),
  INDEX `fk_menu_has_Perfil_Perfil1_idx` (`idPerfil` ASC) VISIBLE,
  INDEX `fk_menu_has_Perfil_menu_idx` (`idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_menu_has_Perfil_menu`
    FOREIGN KEY (`idMenu`)
    REFERENCES `projetoJava`.`menu` (`idMenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_Perfil_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `projetoJava`.`Perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `qtd` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeRazao` VARCHAR(45) NOT NULL,
  `cpfCnpj` VARCHAR(45) NOT NULL,
  `rgIe` VARCHAR(45) NOT NULL,
  `dataNascAbertura` DATE NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `idCliente` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_venda_cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_venda_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `projetoJava`.`cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `projetoJava`.`usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoJava`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoJava`.`venda_produto` (
  `idVenda` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `qtdVendida` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idVenda`, `idProduto`),
  INDEX `fk_Produto_has_venda_venda1_idx` (`idVenda` ASC) VISIBLE,
  INDEX `fk_Produto_has_venda_Produto1_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_venda_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `projetoJava`.`Produto` (`idProduto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produto_has_venda_venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `projetoJava`.`venda` (`idVenda`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -------------------------------------------------------
-- Perfil pré-cadastrado vincular com o usuário
-- ------------------------------------------------------
INSERT INTO Perfil (idPerfil,nome) VALUES
	("1","Administrador");
    
-- ------------------------------------------------------
-- Usuario pré-cadastrador para vincular com o Perfil
-- ------------------------------------------------------
INSERT INTO `usuario`(`idUsuario`, `nome`, `login`, `senha`, `status`, `idPerfil`) VALUES 
("1","Teste","admin","123","1","1");

-- ------------------------------------------------------
-- Menus pré-cadastrados para o usuario primario ter acesso
-- ------------------------------------------------------
INSERT INTO `menu`(`idMenu`, `nome`, `link`, `icone`, `exibir`) VALUES 
("1","Início","index.jsp","","1"),
("2","Perfil","listar_Perfil.jsp","","1"),
("3","Menus","listar_menu.jsp","","1"),
("4","Usuario","listar_usuario.jsp","","1"),
("5","Produto","listar_produto.jsp","","1"),
("6","Cliente","listar_cliente.jsp","","1"),
("7","Cadastrar Perfil","form_perfil.jsp","","2"),
("8","Alterar Perfil","gerenciar_perfil.do?acao=alterar","","2"),
("9","Deletar Perfil","gerenciar_perfil.do?acao=deletar","","2"),
("10","Acessos","gerenciar_menu_perfil.do?acao=gerenciar","","2"),
("11","Formulário Menu Perfil","form_menu_perfil.jsp","","2"),
("12","Alterar Menus","gerenciar_menu.do?acao=alterar","","2"),
("13","Deletar Menu","gerenciar_menu.do?acao=deletar","","2"),
("14","Desvincular Menu Perfil","gerenciar_menu_perfil.do?acao=desvincula","","2"),
("15","Cadastrar Usuario","form_usuario.jsp","","2"),
("16","Alterar Usuario","gerenciar_usuario.do?acao=alterar","","2"),
("17","Deletar Usuario","gerenciar_usuario.do?acao=deletar","","2"),
("18","Cadastrar Produto","form_produto.jsp","","2"),
("19","Alterar Produto","gerenciar_produto.do?acao=alterar","","2"),
("20","Deletar Produto","gerenciar_produto.do?acao=deletar","","2"),
("21","Cadastrar Cliente","form_cliente.jsp","","2"),
("22","Alterar Cliente","gerenciar_cliente.do?acao=alterar","","2"),
("23","Deletar Cliente","gerenciar_cliente.do?acao=deletar","","2"),
("24","Listar Vendas","listar_venda.jsp","","2");



-- -----------------------------------------------------
-- Menus pré-vinculados ao Perfil
-- ------------------------------------------------------
INSERT INTO `menu_perfil`(`idMenu`, `idPerfil`) VALUES 
("1","1"),
("2","1"),
("3","1"),
("4","1"),
("5","1"),
("6","1"),
("7","1"),
("8","1"),
("9","1"),
("10","1"),
("11","1"),
("12","1"),
("13","1"),
("14","1"),
("15","1"),
("16","1"),
("17","1"),
("18","1"),
("19","1"),
("20","1"),
("21","1"),
("22","1"),
("23","1");


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
